package turism.network.rpcprotocol;

public enum RequestType {
    LOGIN, LOGOUT, GET_LOGGED_USERS,
    SEND_REZERVARE, GET_REZERVARI_BY_EXCURSIE,
    GET_EXCURSII, GET_EXCURSII_BY_DESTINATION_AND_DATE, GET_LOCURI_OCUPATE,
    SEND_CLIENT, GET_CLIENT_BY_NAME_AND_PHONE;
}
